# Makefile for USB network drivers from backports

obj-$(CPTCFG_USB_USBNET)		+= usbnet.o
obj-$(CPTCFG_USB_NET_RNDIS_HOST)	+= rndis_host.o
obj-$(CPTCFG_USB_NET_CDC_ETHER)		+= cdc_ether.o
obj-$(CPTCFG_USB_NET_CDC_MBIM)		+= cdc_mbim.o
obj-$(CPTCFG_USB_NET_CDC_NCM)		+= cdc_ncm.o
obj-$(CPTCFG_USB_NET_QMI_WWAN)		+= qmi_wwan.o
obj-$(CPTCFG_USB_NET_SIERRA_NET)	+= sierra_net.o
