# Makefile for backported drivers

obj-$(CPTCFG_SSB)		+= ssb/
obj-$(CPTCFG_BCMA)		+= bcma/
obj-$(CPTCFG_USB_NET_DRIVERS)	+= net/usb/
obj-$(CPTCFG_USB_WDM)		+= usb/class/
obj-$(CPTCFG_WLAN)		+= net/wireless/
obj-$(CPTCFG_STAGING)		+= staging/
