# SPDX-License-Identifier: GPL-2.0
# Backports BCMA driver Makefile
# This directory is currently empty but may be populated in future backports

# No objects to build currently
# obj-$(CPTCFG_BCMA) += bcma.o
